CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS public.items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id TEXT REFERENCES public.sources(id),
    external_id TEXT,
    class TEXT,
    title TEXT,
    description TEXT,
    uf TEXT,
    city TEXT,
    neighborhood TEXT,
    address TEXT,
    lat DOUBLE PRECISION,
    lng DOUBLE PRECISION,
    area_sqm DOUBLE PRECISION,
    rooms INTEGER,
    bathrooms INTEGER,
    parking_spots INTEGER,
    year INTEGER,
    brand TEXT,
    model TEXT,
    appraisal_value DOUBLE PRECISION,
    min_bid DOUBLE PRECISION,
    second_bid DOUBLE PRECISION,
    first_auction_at TIMESTAMPTZ,
    second_auction_at TIMESTAMPTZ,
    auctioneer TEXT,
    process_number TEXT,
    matricula TEXT,
    edital_pdf_url TEXT,
    origin_url TEXT,
    images JSONB,
    raw_payload JSONB,
    embedding vector(1536),
    search_tsv tsvector,
    first_seen_at TIMESTAMPTZ DEFAULT now(),
    last_seen_at TIMESTAMPTZ DEFAULT now(),
    closed_at TIMESTAMPTZ,
    status TEXT DEFAULT 'open',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    edital_extraido JSONB,
    edital_extraido_em TIMESTAMPTZ,
    enriched_at TIMESTAMPTZ,
    comparaveis_atualizado_em TIMESTAMPTZ,
    rental_atualizado_em TIMESTAMPTZ,
    judicial_atualizado_em TIMESTAMPTZ,
    dedup_key TEXT UNIQUE
);
